### PR TITLE
update CMakeLists.txt for preferences files

### PR DESCRIPTION
**Pull request by snakelayer**
I was getting unresolved external symbol errors without this

### CODE REVIEW

**Comment by hairys** [comment]
Thanks. The whole build process needs updating for 64-bit. cmake needs some serious tweaking. I'm sure we'll get to it eventually :)

**Comment by snakelayer** [comment]
Great! Two things:

1. I was trying to build 32-bit when the error was showing up. I don't understand how anyone was successfully building on MSVS without this change.

2. I'd love to know how to make 64-bit builds. I've done some poking and searching, but no luck.

**Comment by hairys** [comment]
Preferences was a recent thing added. Just forgot to add them to CMakeLists.txt. Also, cmake isn't required to setup VS projects, you can always setup projects manually. cmake is purely for convenience.

**Comment by hairys** [comment]
We have to add 64-bit to cmake. We've been setting them up manually in VS. You need to make a new build configuration in VS (x64) and tweak some settings in each of the project properties. There's a lot involved for new build configs, hence the reason they haven't been added to cmake yet.

**Pull request merged**
