### PR TITLE
Cleaner project, faster project setup

### PR DESCRIPTION
**Pull request by Cubimon**

### CODE REVIEW

**Comment by sm-k** [comment]
hi - thanks for this. this was really helpful in getting the project up and running. however there are references to thread.Crits.cpp or something which doesn't exist, causing bootstrap to fail

**Comment by frifox** [comment]
Pushed the missing file to main branch.

**Comment by Cubimon** [comment]
The only problem I had with the bootstrap script was the windows fs. If one application has a file handle open another application cannot read or write to the same file. That's why the bootstrap.bat cannot copy itself unless it terminates (then it works, but it still throws an error). So what do you mean by reference or can you specify your problem?

**Comment by sm-k** [comment]
i mean bootstrap was looking for a file called thread.Crits.cpp which didn't exist in frifox's original repo and as a result didn't exist in yours

**Comment by Cubimon** [comment]
Now I see it I will add this file tomorrow. Thx for mentioning

**Pull request merged**
