### PR TITLE
Update Gadget and World Boss HP offsets for 64-bit

### PR DESCRIPTION
**Pull request by hairys**
also added breakbar state check.

### CODE REVIEW

**Comment by hairys** [comment]
Guess I can't make a separate pull request, haha. It lumped my float changes into my previous pull request.

**Comment by frifox** [comment]
gw2dps.cpp lines 289/290, probably meant hp_shift_xxx, not hp_shift1_xxx.
Also, the Ally struct in the gw2dps.h was missing "Vector pos;"

Btw, I did try to get a x64 build to work, but for some reason it's not even injecting (no console) for me, odd. I'll mess a bit more but it's quite late, might have to continue tomorrow.

**Comment by hairys** [comment]
Yep, meant hp_shift_xxx, thanks. It's 4 hours past my bedtime....
x64 built is working for me. Finally. I did have an issue with the screen freezing upon injecting. Rafzi was able to fix it. It was an error with the hkPresent hook, as I suspected.

**Comment by frifox** [comment]
Yup, not going to happen today. For me it fails at CreateRemoteThread part when injecting. I tried few x64 injectors I found online but even though they tell me injection was successful, nothing really happened.

**Comment by Shawn538** [comment]
UGH! i want to help sooooooo bad! But i only know java... Ive taken it upon myself to learn some C++ so i can try to aid in the conversion to 64. But i cant seem to get a fucking compiler to function on my computer at all. Tried eclipse.. but it wont even run a simple hello world. Im so mad cause im so bad

**Comment by hairys** [comment]
@frifox switch your entire build environment to 64-bit. That includes external libraries (boost, wxWidgets, direct x, etc). You'll have to build everything from scratch in 64-bit mode.

**Comment by hairys** [comment]
We'll have to make them as entirely separate builds for now. I tried to do some integration yolo mouse style. They use a single (x64) exe to inject either a 64-bit or 32-bit dll. That's what I want to try to do.

**Comment by hairys** [comment]
@Shawn538 get Microsoft's Visual Studio 2013 Community edition. It supports 64-bit compile.

**Comment by Shawn538** [comment]
@hairys After many many hours of trying to figure it out... i finally got it to compile a program... and i even figured out how to distribute it to my friends (the basic hello world i made).

now i can do the helps (or try to) :D

**Comment by hairys** [comment]
I managed to make a single (x86) injector that can inject either the 32-bit or 64-bit dll by using a 64-bit proxy exe.

**Pull request merged**
